### ISSUE TITLE
incorrect test for context transformations

### ISSUE THREAD

**Issue by lars-petter-hauge** [equinor/configsuite#104]
While working on a different issue I noticed that the key in the setup here is incorrect: https://github.com/equinor/configsuite/blob/1998280b2fb61defa681ab660c8a87434e96a0d9/tests/test_context_element_validators.py#L59

It looks like a spelling error instead of an intended fault, could it be a bug?

Furthermore I wonder what this test is supposed to do. It states that it is supposed to test that without a context you shouldn't get a crash. Is that tested implicitly by saying the validation of the config should hit an issue in advance?

If my assumption about spelling error is correct, this would hit an `InvalidTypeError`, otherwise it will hit an `UnknownKeyError` error.

**Comment by markusdregi** [comment]
Well spotted! You are indeed correct. I've fixed the typo and added a check to verify that it is indeed an `InvalidTypeError` that comes out on the other side...

When it comes to what the test is to test, the above test is to verify that the code handles the case when the data that is the foundation of the context is not valid and hence an empty context will be passed to the validators.

**Comment by lars-petter-hauge** [comment]
Ah, I missed the flow here.

```
