### ISSUE TITLE
Way to specify that a list or collection is required, ie have at least one valid entry 

### ISSUE THREAD

**Issue by eivindsm** [equinor/configsuite#149]
With the required method being deprecated it is more difficult to specify a schema with a required list or collection, that has to have at least one valid entry. Currently this has to be done through a validator, which is kind of technical for Jo the engineer.  Propose to add built inn option to specify this in the schema definition.

**Comment by markusdregi** [comment]
Thanks for the input @eivindsm! Do you agree this address the same problem? If so, I'll close #148 as a duplicate 👍 

> A very common behaviour is to disallow empty containers (list and dict). It is a bit odd consumers have to write validators for this. I would hence suggest that we start supporting this natively in the schema. My proposed solution would be to implement:
>
> `MetaKeys.AllowEmpty -> [True, False]`
>
> for list and dict.

**Comment by eivindsm** [comment]
Yes, sure this addresses the same problem. pls close my duplicate :)

**Comment by markusdregi** [comment]
I'll keep the one coming from the community open ;)
