### ISSUE TITLE
Setup CircleCI

### ISSUE THREAD

**Issue by markusdregi** [equinor/configsuite#76]
Add CircleCI

**Comment by markusdregi** [comment]
@jondequinor @sondreso You could have a look at this one

**Comment by semafor** [comment]
Is there an existing Organization in CircleCI, or are we creating a test organization?

**Comment by markusdregi** [comment]
_Equinor_ exists.

**Comment by semafor** [comment]
Okay, then we'll need repo administration privileges.

**Comment by jondequinor** [comment]
To allow circleci to upload to codacy, we'll need a codacy token.

If we want to migrate fully to circleci, we'll need a pypi token.

**Comment by markusdregi** [comment]
I was thinking that we could leave that for later...? That getting the pipeline up and running with tests and doc building would suffice for now.
